window.esdocSearchIndex = [
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstoreaddoptions",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html",
    "<span>JSONStoreAddOptions</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstorechangeoptions",
    "class/js/JSONStoreChangeOptions.js~JSONStoreChangeOptions.html",
    "<span>JSONStoreChangeOptions</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstorecollection",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html",
    "<span>JSONStoreCollection</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstorefindoptions",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html",
    "<span>JSONStoreFindOptions</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstoreinitoptions",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html",
    "<span>JSONStoreInitOptions</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstorequerypart",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html",
    "<span>JSONStoreQueryPart</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~jsonstoresyncpolicy",
    "class/js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.html",
    "<span>JSONStoreSyncPolicy</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~wljsonstore",
    "class/js/WLJSONStore.js~WLJSONStore.html",
    "<span>WLJSONStore</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "react-native-ibm-mobilefirst-jsonstore~wllogger",
    "class/js/WLLogger.js~WLLogger.html",
    "<span>WLLogger</span> <span class=\"search-result-import-path\">react-native-ibm-mobilefirst-jsonstore</span>",
    "class"
  ],
  [
    "js/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "js/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "js/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "js/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "js/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "js/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "js/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "js/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "js/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "js/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "js/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "js/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "js/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "js/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "js/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "js/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "js/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "js/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "js/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "js/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "js/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "js/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "js/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "js/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "js/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "js/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "js/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "js/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "js/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "js/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "js/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "js/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "js/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "js/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "js/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "js/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "js/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "js/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "js/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "js/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "js/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "js/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "js/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "js/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "js/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "js/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "js/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "js/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "js/.external-ecmascript.js~String",
    "external"
  ],
  [
    "js/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "js/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "js/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "js/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "js/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "js/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "js/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "js/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "js/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "js/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "js/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "js/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "js/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "js/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "js/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "js/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "js/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "js/.external-ecmascript.js~function",
    "external"
  ],
  [
    "js/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "js/.external-ecmascript.js~null",
    "external"
  ],
  [
    "js/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "js/.external-ecmascript.js~number",
    "external"
  ],
  [
    "js/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "js/.external-ecmascript.js~object",
    "external"
  ],
  [
    "js/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "js/.external-ecmascript.js~string",
    "external"
  ],
  [
    "js/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "js/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "js/jsonstoreaddoptions.js",
    "file/js/JSONStoreAddOptions.js.html",
    "js/JSONStoreAddOptions.js",
    "file"
  ],
  [
    "js/jsonstoreaddoptions.js~jsonstoreaddoptions#addadditionalsearchfield",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html#instance-method-addAdditionalSearchField",
    "js/JSONStoreAddOptions.js~JSONStoreAddOptions#addAdditionalSearchField",
    "method"
  ],
  [
    "js/jsonstoreaddoptions.js~jsonstoreaddoptions#addadditionalsearchfields",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html#instance-method-addAdditionalSearchFields",
    "js/JSONStoreAddOptions.js~JSONStoreAddOptions#addAdditionalSearchFields",
    "method"
  ],
  [
    "js/jsonstoreaddoptions.js~jsonstoreaddoptions#additionalsearchfields",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html#instance-member-additionalSearchFields",
    "js/JSONStoreAddOptions.js~JSONStoreAddOptions#additionalSearchFields",
    "member"
  ],
  [
    "js/jsonstoreaddoptions.js~jsonstoreaddoptions#constructor",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html#instance-constructor-constructor",
    "js/JSONStoreAddOptions.js~JSONStoreAddOptions#constructor",
    "method"
  ],
  [
    "js/jsonstoreaddoptions.js~jsonstoreaddoptions#markdirty",
    "class/js/JSONStoreAddOptions.js~JSONStoreAddOptions.html#instance-member-markDirty",
    "js/JSONStoreAddOptions.js~JSONStoreAddOptions#markDirty",
    "member"
  ],
  [
    "js/jsonstorechangeoptions.js",
    "file/js/JSONStoreChangeOptions.js.html",
    "js/JSONStoreChangeOptions.js",
    "file"
  ],
  [
    "js/jsonstorechangeoptions.js~jsonstorechangeoptions#addnew",
    "class/js/JSONStoreChangeOptions.js~JSONStoreChangeOptions.html#instance-member-addNew",
    "js/JSONStoreChangeOptions.js~JSONStoreChangeOptions#addNew",
    "member"
  ],
  [
    "js/jsonstorechangeoptions.js~jsonstorechangeoptions#constructor",
    "class/js/JSONStoreChangeOptions.js~JSONStoreChangeOptions.html#instance-constructor-constructor",
    "js/JSONStoreChangeOptions.js~JSONStoreChangeOptions#constructor",
    "method"
  ],
  [
    "js/jsonstorechangeoptions.js~jsonstorechangeoptions#markdirty",
    "class/js/JSONStoreChangeOptions.js~JSONStoreChangeOptions.html#instance-member-markDirty",
    "js/JSONStoreChangeOptions.js~JSONStoreChangeOptions#markDirty",
    "member"
  ],
  [
    "js/jsonstorechangeoptions.js~jsonstorechangeoptions#searchfieldcriteria",
    "class/js/JSONStoreChangeOptions.js~JSONStoreChangeOptions.html#instance-member-searchFieldCriteria",
    "js/JSONStoreChangeOptions.js~JSONStoreChangeOptions#searchFieldCriteria",
    "member"
  ],
  [
    "js/jsonstorecollection.js",
    "file/js/JSONStoreCollection.js.html",
    "js/JSONStoreCollection.js",
    "file"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#adddata",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-addData",
    "js/JSONStoreCollection.js~JSONStoreCollection#addData",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#changedata",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-changeData",
    "js/JSONStoreCollection.js~JSONStoreCollection#changeData",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#clearcollection",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-clearCollection",
    "js/JSONStoreCollection.js~JSONStoreCollection#clearCollection",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#constructor",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-constructor-constructor",
    "js/JSONStoreCollection.js~JSONStoreCollection#constructor",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#countalldirtydocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-countAllDirtyDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#countAllDirtyDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#countalldocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-countAllDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#countAllDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#countdocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-countDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#countDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#findalldirtydocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-findAllDirtyDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#findAllDirtyDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#findalldocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-findAllDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#findAllDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#finddocumentbyid",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-findDocumentById",
    "js/JSONStoreCollection.js~JSONStoreCollection#findDocumentById",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#finddocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-findDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#findDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#finddocumentsbyid",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-findDocumentsById",
    "js/JSONStoreCollection.js~JSONStoreCollection#findDocumentsById",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#getadditionalsearchfields",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-getAdditionalSearchFields",
    "js/JSONStoreCollection.js~JSONStoreCollection#getAdditionalSearchFields",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#getsearchfields",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-getSearchFields",
    "js/JSONStoreCollection.js~JSONStoreCollection#getSearchFields",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#hasadditionalsearchfield",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-hasAdditionalSearchField",
    "js/JSONStoreCollection.js~JSONStoreCollection#hasAdditionalSearchField",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#hassearchfield",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-hasSearchField",
    "js/JSONStoreCollection.js~JSONStoreCollection#hasSearchField",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#isdocumentdirty",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-isDocumentDirty",
    "js/JSONStoreCollection.js~JSONStoreCollection#isDocumentDirty",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#markdocumentclean",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-markDocumentClean",
    "js/JSONStoreCollection.js~JSONStoreCollection#markDocumentClean",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#markdocumentsclean",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-markDocumentsClean",
    "js/JSONStoreCollection.js~JSONStoreCollection#markDocumentsClean",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#removecollection",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-removeCollection",
    "js/JSONStoreCollection.js~JSONStoreCollection#removeCollection",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#removedocumentbyid",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-removeDocumentById",
    "js/JSONStoreCollection.js~JSONStoreCollection#removeDocumentById",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#removedocumentsbyid",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-removeDocumentsById",
    "js/JSONStoreCollection.js~JSONStoreCollection#removeDocumentsById",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#replacedocument",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-replaceDocument",
    "js/JSONStoreCollection.js~JSONStoreCollection#replaceDocument",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#replacedocuments",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-replaceDocuments",
    "js/JSONStoreCollection.js~JSONStoreCollection#replaceDocuments",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#setadditionalsearchfield",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-setAdditionalSearchField",
    "js/JSONStoreCollection.js~JSONStoreCollection#setAdditionalSearchField",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#setsearchfield",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-setSearchField",
    "js/JSONStoreCollection.js~JSONStoreCollection#setSearchField",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#sync",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-sync",
    "js/JSONStoreCollection.js~JSONStoreCollection#sync",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection#wasreopened",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#instance-method-wasReopened",
    "js/JSONStoreCollection.js~JSONStoreCollection#wasReopened",
    "method"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection.boolean",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#static-get-BOOLEAN",
    "js/JSONStoreCollection.js~JSONStoreCollection.BOOLEAN",
    "member"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection.integer",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#static-get-INTEGER",
    "js/JSONStoreCollection.js~JSONStoreCollection.INTEGER",
    "member"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection.number",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#static-get-NUMBER",
    "js/JSONStoreCollection.js~JSONStoreCollection.NUMBER",
    "member"
  ],
  [
    "js/jsonstorecollection.js~jsonstorecollection.string",
    "class/js/JSONStoreCollection.js~JSONStoreCollection.html#static-get-STRING",
    "js/JSONStoreCollection.js~JSONStoreCollection.STRING",
    "member"
  ],
  [
    "js/jsonstorefindoptions.js",
    "file/js/JSONStoreFindOptions.js.html",
    "js/JSONStoreFindOptions.js",
    "file"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#addfilter",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-method-addFilter",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#addFilter",
    "method"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#addsortascending",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-method-addSortAscending",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#addSortAscending",
    "method"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#addsortdescending",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-method-addSortDescending",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#addSortDescending",
    "method"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#constructor",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-constructor-constructor",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#constructor",
    "method"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#filters",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-member-filters",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#filters",
    "member"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#limit",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-member-limit",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#limit",
    "member"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#offset",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-member-offset",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#offset",
    "member"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#sortascending",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-member-sortAscending",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#sortAscending",
    "member"
  ],
  [
    "js/jsonstorefindoptions.js~jsonstorefindoptions#sortdescending",
    "class/js/JSONStoreFindOptions.js~JSONStoreFindOptions.html#instance-member-sortDescending",
    "js/JSONStoreFindOptions.js~JSONStoreFindOptions#sortDescending",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js",
    "file/js/JSONStoreInitOptions.js.html",
    "js/JSONStoreInitOptions.js",
    "file"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#constructor",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-constructor-constructor",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#constructor",
    "method"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#enableanalytics",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-enableAnalytics",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#enableAnalytics",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#password",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-password",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#password",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#pbkdf2iterations",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-pbkdf2Iterations",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#pbkdf2Iterations",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#securerandom",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-secureRandom",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#secureRandom",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#setsyncoptions",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-method-setSyncOptions",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#setSyncOptions",
    "method"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#syncadapterpath",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-syncAdapterPath",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#syncAdapterPath",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#syncpolicy",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-syncPolicy",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#syncPolicy",
    "member"
  ],
  [
    "js/jsonstoreinitoptions.js~jsonstoreinitoptions#username",
    "class/js/JSONStoreInitOptions.js~JSONStoreInitOptions.html#instance-member-username",
    "js/JSONStoreInitOptions.js~JSONStoreInitOptions#username",
    "member"
  ],
  [
    "js/jsonstorequerypart.js",
    "file/js/JSONStoreQueryPart.js.html",
    "js/JSONStoreQueryPart.js",
    "file"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addbetween",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addBetween",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addBetween",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addequal",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addEqual",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addEqual",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addgreaterthan",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addGreaterThan",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addGreaterThan",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addgreaterthanorequal",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addGreaterThanOrEqual",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addGreaterThanOrEqual",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addinside",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addInside",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addInside",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addleftlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addLeftLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addLeftLike",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addlessthan",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addLessThan",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addLessThan",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addlessthanorequal",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addLessThanOrEqual",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addLessThanOrEqual",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addLike",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotbetween",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotBetween",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotBetween",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotequal",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotEqual",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotEqual",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotinside",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotInside",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotInside",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotleftlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotLeftLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotLeftLike",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotLike",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addnotrightlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addNotRightLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addNotRightLike",
    "method"
  ],
  [
    "js/jsonstorequerypart.js~jsonstorequerypart#addrightlike",
    "class/js/JSONStoreQueryPart.js~JSONStoreQueryPart.html#instance-method-addRightLike",
    "js/JSONStoreQueryPart.js~JSONStoreQueryPart#addRightLike",
    "method"
  ],
  [
    "js/jsonstoresyncpolicy.js",
    "file/js/JSONStoreSyncPolicy.js.html",
    "js/JSONStoreSyncPolicy.js",
    "file"
  ],
  [
    "js/jsonstoresyncpolicy.js~jsonstoresyncpolicy#type",
    "class/js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.html#instance-member-type",
    "js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy#type",
    "member"
  ],
  [
    "js/jsonstoresyncpolicy.js~jsonstoresyncpolicy.sync_downstream",
    "class/js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.html#static-get-SYNC_DOWNSTREAM",
    "js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.SYNC_DOWNSTREAM",
    "member"
  ],
  [
    "js/jsonstoresyncpolicy.js~jsonstoresyncpolicy.sync_none",
    "class/js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.html#static-get-SYNC_NONE",
    "js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.SYNC_NONE",
    "member"
  ],
  [
    "js/jsonstoresyncpolicy.js~jsonstoresyncpolicy.sync_upstream",
    "class/js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.html#static-get-SYNC_UPSTREAM",
    "js/JSONStoreSyncPolicy.js~JSONStoreSyncPolicy.SYNC_UPSTREAM",
    "member"
  ],
  [
    "js/utils.js",
    "file/js/Utils.js.html",
    "js/Utils.js",
    "file"
  ],
  [
    "js/wljsonstore.js",
    "file/js/WLJSONStore.js.html",
    "js/WLJSONStore.js",
    "file"
  ],
  [
    "js/wljsonstore.js~wljsonstore#changepassword",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-changePassword",
    "js/WLJSONStore.js~WLJSONStore#changePassword",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#closeall",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-closeAll",
    "js/WLJSONStore.js~WLJSONStore#closeAll",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#committransaction",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-commitTransaction",
    "js/WLJSONStore.js~WLJSONStore#commitTransaction",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#destroy",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-destroy",
    "js/WLJSONStore.js~WLJSONStore#destroy",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#getfileinfo",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-getFileInfo",
    "js/WLJSONStore.js~WLJSONStore#getFileInfo",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#opencollections",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-openCollections",
    "js/WLJSONStore.js~WLJSONStore#openCollections",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#rollbacktransaction",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-rollbackTransaction",
    "js/WLJSONStore.js~WLJSONStore#rollbackTransaction",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#setanalyticsenabled",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-setAnalyticsEnabled",
    "js/WLJSONStore.js~WLJSONStore#setAnalyticsEnabled",
    "method"
  ],
  [
    "js/wljsonstore.js~wljsonstore#starttransaction",
    "class/js/WLJSONStore.js~WLJSONStore.html#instance-method-startTransaction",
    "js/WLJSONStore.js~WLJSONStore#startTransaction",
    "method"
  ],
  [
    "js/wllogger.js",
    "file/js/WLLogger.js.html",
    "js/WLLogger.js",
    "file"
  ],
  [
    "js/wllogger.js~wllogger#constructor",
    "class/js/WLLogger.js~WLLogger.html#instance-constructor-constructor",
    "js/WLLogger.js~WLLogger#constructor",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#debug",
    "class/js/WLLogger.js~WLLogger.html#instance-method-debug",
    "js/WLLogger.js~WLLogger#debug",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#debugwithmetadata",
    "class/js/WLLogger.js~WLLogger.html#instance-method-debugWithMetadata",
    "js/WLLogger.js~WLLogger#debugWithMetadata",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#error",
    "class/js/WLLogger.js~WLLogger.html#instance-method-error",
    "js/WLLogger.js~WLLogger#error",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#errorwithmetadata",
    "class/js/WLLogger.js~WLLogger.html#instance-method-errorWithMetadata",
    "js/WLLogger.js~WLLogger#errorWithMetadata",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#getcapture",
    "class/js/WLLogger.js~WLLogger.html#instance-method-getCapture",
    "js/WLLogger.js~WLLogger#getCapture",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#getfilters",
    "class/js/WLLogger.js~WLLogger.html#instance-method-getFilters",
    "js/WLLogger.js~WLLogger#getFilters",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#getlevel",
    "class/js/WLLogger.js~WLLogger.html#instance-method-getLevel",
    "js/WLLogger.js~WLLogger#getLevel",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#getmaxfilesize",
    "class/js/WLLogger.js~WLLogger.html#instance-method-getMaxFileSize",
    "js/WLLogger.js~WLLogger#getMaxFileSize",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#info",
    "class/js/WLLogger.js~WLLogger.html#instance-method-info",
    "js/WLLogger.js~WLLogger#info",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#infowithmetadata",
    "class/js/WLLogger.js~WLLogger.html#instance-method-infoWithMetadata",
    "js/WLLogger.js~WLLogger#infoWithMetadata",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#logtag",
    "class/js/WLLogger.js~WLLogger.html#instance-member-logTag",
    "js/WLLogger.js~WLLogger#logTag",
    "member"
  ],
  [
    "js/wllogger.js~wllogger#send",
    "class/js/WLLogger.js~WLLogger.html#instance-method-send",
    "js/WLLogger.js~WLLogger#send",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#setcapture",
    "class/js/WLLogger.js~WLLogger.html#instance-method-setCapture",
    "js/WLLogger.js~WLLogger#setCapture",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#setfilters",
    "class/js/WLLogger.js~WLLogger.html#instance-method-setFilters",
    "js/WLLogger.js~WLLogger#setFilters",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#setlevel",
    "class/js/WLLogger.js~WLLogger.html#instance-method-setLevel",
    "js/WLLogger.js~WLLogger#setLevel",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#setmaxfilesize",
    "class/js/WLLogger.js~WLLogger.html#instance-method-setMaxFileSize",
    "js/WLLogger.js~WLLogger#setMaxFileSize",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#trace",
    "class/js/WLLogger.js~WLLogger.html#instance-method-trace",
    "js/WLLogger.js~WLLogger#trace",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#tracewithmetadata",
    "class/js/WLLogger.js~WLLogger.html#instance-method-traceWithMetadata",
    "js/WLLogger.js~WLLogger#traceWithMetadata",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#updateconfigfromserver",
    "class/js/WLLogger.js~WLLogger.html#instance-method-updateConfigFromServer",
    "js/WLLogger.js~WLLogger#updateConfigFromServer",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#warn",
    "class/js/WLLogger.js~WLLogger.html#instance-method-warn",
    "js/WLLogger.js~WLLogger#warn",
    "method"
  ],
  [
    "js/wllogger.js~wllogger#warnwithmetadata",
    "class/js/WLLogger.js~WLLogger.html#instance-method-warnWithMetadata",
    "js/WLLogger.js~WLLogger#warnWithMetadata",
    "method"
  ],
  [
    "js/wllogger.js~wllogger.debug",
    "class/js/WLLogger.js~WLLogger.html#static-get-DEBUG",
    "js/WLLogger.js~WLLogger.DEBUG",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.error",
    "class/js/WLLogger.js~WLLogger.html#static-get-ERROR",
    "js/WLLogger.js~WLLogger.ERROR",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.fatal",
    "class/js/WLLogger.js~WLLogger.html#static-get-FATAL",
    "js/WLLogger.js~WLLogger.FATAL",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.info",
    "class/js/WLLogger.js~WLLogger.html#static-get-INFO",
    "js/WLLogger.js~WLLogger.INFO",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.log",
    "class/js/WLLogger.js~WLLogger.html#static-get-LOG",
    "js/WLLogger.js~WLLogger.LOG",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.trace",
    "class/js/WLLogger.js~WLLogger.html#static-get-TRACE",
    "js/WLLogger.js~WLLogger.TRACE",
    "member"
  ],
  [
    "js/wllogger.js~wllogger.warn",
    "class/js/WLLogger.js~WLLogger.html#static-get-WARN",
    "js/WLLogger.js~WLLogger.WARN",
    "member"
  ]
]