FROM nginx:alpine
COPY ./api-ref /usr/share/nginx/html/api-ref
COPY ./webinars /usr/share/nginx/html/webinars
COPY ./sitemap.xml /usr/share/nginx/html/sitemap.xml
COPY ./feed.xml /usr/share/nginx/html/feed.xml
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./video-gallery /usr/share/nginx/html/video-gallery
COPY ./third-party-notice /usr/share/nginx/html/third-party-notice
COPY ./terms-of-use /usr/share/nginx/html/terms-of-use
COPY ./search /usr/share/nginx/html/search
COPY ./newsletter /usr/share/nginx/html/newsletter
COPY ./legal-notices /usr/share/nginx/html/legal-notices
COPY ./learn-more /usr/share/nginx/html/learn-more
COPY ./labs /usr/share/nginx/html/labs
COPY ./js /usr/share/nginx/html/js
COPY ./help /usr/share/nginx/html/help
COPY ./features /usr/share/nginx/html/features
COPY ./css /usr/share/nginx/html/css
COPY ./beta /usr/share/nginx/html/beta
COPY ./assets /usr/share/nginx/html/assets
COPY ./Staticfile /usr/share/nginx/html/Staticfile
COPY ./404 /usr/share/nginx/html/404
COPY ./404-archived /usr/share/nginx/html/404-archived
COPY ./robots.txt /usr/share/nginx/html/robots.txt
COPY ./onboarding.md /usr/share/nginx/html/onboarding.md
COPY ./contributing.md /usr/share/nginx/html/contributing.md
COPY ./nginx.conf /usr/share/nginx/html/nginx.conf
COPY ./licenses /usr/share/nginx/html/licenses
COPY ./lib /usr/share/nginx/html/lib
COPY ./fonts /usr/share/nginx/html/fonts
COPY ./google099f4cf7fee9e5fc.html /usr/share/nginx/html/google099f4cf7fee9e5fc.html
COPY ./favicon.png /usr/share/nginx/html/favicon.png
COPY ./favicon.ico /usr/share/nginx/html/favicon.ico
COPY ./container-nginx.conf.deployment /usr/share/nginx/html/container-nginx.conf.deployment
COPY ./LICENSE /usr/share/nginx/html/LICENSE
COPY ./Dockerfile /usr/share/nginx/html/Dockerfile
COPY ./tutorials/ja /usr/share/nginx/html/tutorials/ja
COPY ./tutorials/ru /usr/share/nginx/html/tutorials/ru
COPY ./tutorials/it /usr/share/nginx/html/tutorials/it
COPY ./tutorials/zh-hans /usr/share/nginx/html/tutorials/zh-hans
COPY ./tutorials/ko /usr/share/nginx/html/tutorials/ko
COPY ./tutorials/pt-br /usr/share/nginx/html/tutorials/pt-br
COPY ./tutorials/de /usr/share/nginx/html/tutorials/de
COPY ./tutorials/fr /usr/share/nginx/html/tutorials/fr
COPY ./tutorials/es /usr/share/nginx/html/tutorials/es
COPY ./tutorials/index.html /usr/share/nginx/html/tutorials/index.html
COPY ./downloads /usr/share/nginx/html/downloads
COPY ./blog /usr/share/nginx/html/blog
COPY ./tutorials/en /usr/share/nginx/html/tutorials/en
