source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-feed'
gem 'redcarpet'
gem 'jekyll-paginate'
# gem 'jekyll-redirect-from'
gem 'html-proofer'
gem 'wkhtmltopdf-binary'
gem 'pdfkit'
gem 'pry'
gem 'pry-byebug'
