source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-feed'
gem 'redcarpet'
gem 'jekyll-paginate'
gem 'html-proofer'
gem 'wkhtmltopdf-binary-edge'
gem 'pdfkit'
gem 'jekyll-sitemap'
# gem 'jekyll-git_metadata', :git => "git://github.com/nasht00/jekyll-git_metadata.git"
# gem 'pry'
# gem 'pry-byebug'
